[workspace]
resolver = "2"
members = ["egui-nav", "examples/*"]

[workspace.package]
edition = "2021"
license = "MIT"

[workspace.dependencies]
egui_nav = { path = "egui-nav" }
egui = "0.28.1"
egui_extras = "0.28.1"
eframe = "0.28.1"
egui_demo_lib = "0.28.1"
